number = list(map(int, input().split(' ')))
# number_copy_1 = number.copy()
# number_copy_2 = number.copy()
print(f"The minimum number is {min(number)}")
print(f"The maximum number is {max(number)}")
print(f"The sum number is: {sum(number)}")